### ISSUE TITLE
Documentation for training

### ISSUE THREAD

**Issue by bsipos** [hyeshik/poreplex#12]
It is great that poreplex has the pipeline for barcoding model training included. However a minimal documentation on how to do the training would be really helpful.

Regards,
Botond

**Comment by a-slide** [comment]
Hi Hyeshik
I would also like to expand the set of barcodes, but I cannot figure out how the training works. A documentation (even a short one) would be much appreciated.
Thanks for the new release by the way, I haven't gave it a try yet but it looks fab.
Cheers
Ad
