### ISSUE TITLE
squiggle scaling?

### ISSUE THREAD

**Issue by Huanle** [hyeshik/poreplex#13]
@hyeshik ,

it seems the dumped adapter squiggles have been re-scaled by poreplex?

Raw: 
![image](https://user-images.githubusercontent.com/909201/49345588-30876e80-f687-11e8-85eb-652f391cc101.png)

Poreplex:
![image](https://user-images.githubusercontent.com/909201/49345591-38471300-f687-11e8-90d7-52587a67fd1f.png)

Can you please tell me the formula for the conversion?
Also, is this necessary?

Thanks a lot

**Comment by hyeshik** [comment]
Hi @Huanle,

Pooreplex provides two types of scaled signals, `mean` and `scaled_mean`. The former is calculated by the simple conversion to pA scale using the formula defined by the digitization parameters in FAST5. Please refer to the ONT's technical documents for the exact formula.

`scaled_mean` is the one poreplex use for the most part of its analysis. It is derived from `mean`, and it is further scaled by a recurrent neural network model shipped with the poreplex distribution. Many types of squiggle analysis become simpler by this RNN-based normalization, but some types of analyses do not receive any benefit from it. I recommend you to use the original raw signal if you need to feed the signal to other software.

Hyeshik

**Comment by Huanle** [comment]
Thanks a lot hyeshik.
But where can i find information of adapter start and end?

**Comment by hyeshik** [comment]
They are available as HDF5 attributes in each dataset entry in the basecalled events outputs.

```python
>>> import h5py
>>> ff = h5py.File('poreplex.Set180606/events/inventory.h5', 'r')
>>> dict(ff['basecalled_events/000/00039824-9618-464e-ac21-942e1f79d1a5'].attrs)
{'signal_scale': 1.0291171, 'signal_shift': 2.3550591, 'adapter_begin': 2805, 'adapter_end': 10050,  'polya_begin': 11699, 'polya_end': 14963, 'spikes': b'[]'}
```

**Comment by Huanle** [comment]
Hi @hyeshik ,

thanks a lot. this is very helpful.
