### ISSUE TITLE
how to get polya length in nts?

### ISSUE THREAD

**Issue by Huanle** [hyeshik/poreplex#15]
Hi Hyeshik,
How to convert polya squiggles into length measured in nucleotides? 
polya squiggle length / full squiggle length (duration)  * sequence length ?
What is polya_dwell in the summary file? Time taken to sequence polyA?
Thanks a lot.

**Comment by hyeshik** [comment]
Hi Huanle,
We're still in studying the relationship between the physical length of a poly(A) tail and the dwell time migrating through a nanopore. What we can sure at this stage yet is that the relationship is hard to model with a simple linear function with one or two coefficients calculated from the neighboring signals. I guess I would be able to add poly(A) length in nt after exploring the measurements from several trials of poly(A) standards. Still, the bare poly(A) dwell time can be a good statistic when comparing between samples sequenced together in parallel.

**Comment by Huanle** [comment]
Thanks @hyeshik .
I look forward to the update on polya length reported in nts. :)

**Comment by Huanle** [comment]
Hi @hyeshik ,
Is there any progress on this specific topic?
Thanks.
