### ISSUE TITLE
Custom barcodes

### ISSUE THREAD

**Issue by Huanle** [hyeshik/poreplex#2]
if i use custom barcodes, do I need to re-train the program?

Thanks. 

Huanlee

**Comment by hyeshik** [comment]
Hi Huanle,

Yes. Since poreplex detects the barcodes in the signal-level, the model needs to be re-trained every time a new adapter is added. There's a pipeline for training in the `training` directory.

**Comment by Huanle** [comment]
@hyeshik 
thanks very much. i will give it a go.
