### ISSUE TITLE
Barcodes

### ISSUE THREAD

**Issue by teshomeb** [hyeshik/poreplex#5]
Is it possible to add more barcodes other than the four DNA barcodes listed. For example, oxford nanopre RTA 
>BC5_OligoA
/5Phos/GGCTTCTTCTTGCTCTTAGGTAGTAGGTTC
>BC5_OligoB
GAGGCGAGCGGTCAATTTTCCTAAGAGCAAGAAGAAGCCTTTTTTTTTT

**Comment by hyeshik** [comment]
To add a support for more adapters, we need raw signal files (at least 100k reads per barcode) generated using *all* of the barcodes to be supported.

The current model in the official package was trained with a pooled sample of four DRS libraries as follows:
- Barcode 1 with A. thaliana leaf total RNA
- Barcode 2 with human colorectal cancer cell line total RNA
- Barcode 3 with S. cerevisiae total RNA
- Barcode 4 with C. elegans total RNA

I think, to scale up for more barcodes, using two or three different in vitro transcribed & polyadenylated RNAs for each barcode would work, too.
