### ISSUE TITLE
Extremely short sequences passing after adapter trimming

### ISSUE THREAD

**Issue by NatPRoach** [hyeshik/poreplex#6]
Hello,
Looking through my data after adapter trimming I've noticed that some of the passing sequences are extremely short (some as short as 4 bp). I'm wondering if there's a means of setting a minimum sequence length that gets to pass. I can write something up myself if not, but I thought it was worth bringing up here in case it wasn't a known issue.

**Comment by hyeshik** [comment]
Thanks for the good suggestion! That would be nice to have as an option. I'll add it soon.
